name: country-clustering
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas=1.5
  - numpy=1.21
  - scikit-learn=1.2
  - matplotlib=3.5
  - seaborn=0.11
  - jupyter=1.0
  - pip
  - pip:
    - openpyxl>=3.0.10
